{"uid":"5ed462220228c9","name":"Create a new Category","fullName":"TestInventory.TestInventory#test_Add_newCategory_1___frugal_latido_com_np____Test_123____E___POM_for_Bottle__WebApp__TestData__InventoryData__Image__BikerJacket_jpg____Leather01____LT01____This_is_from_an_automated_Script___for_Leather___01___1__None_","historyId":"607bd8098e4df3770a5af8b545d08ef1","time":{"start":1685108467661,"stop":1685108483075,"duration":15414},"status":"failed","statusMessage":"AssertionError: None != True : Adding a New Category Failed","statusTrace":"self = <TestsCases.TestInventory.TestInventory testMethod=test_Add_newCategory_1___frugal_latido_com_np____Test_123____E___PO...oryData__Image__BikerJacket_jpg____Leather01____LT01____This_is_from_an_automated_Script___for_Leather___01___1__None_>\nusername = 'frugal@latido.com.np', password = 'Test@123'\nImagePath = 'E:\\\\POM_for_Bottle\\\\WebApp\\\\TestData\\\\InventoryData\\\\Image\\\\BikerJacket.jpg'\nname = 'Leather01', code = 'LT01'\ndesc = 'This is from an automated Script ( for Leather ) 01', leather_flag = 1\nunit = None\n\n    @allure.title(f\"Create a new Category\")\n    @allure.story(\"Create a new Category from Add button \")\n    @allure.severity(allure.severity_level.NORMAL)\n    @data(*Utils.read_xlsx(\"../TestData/InventoryData/InventoryTestCase.xlsx\", \"TestInventory\"))\n    @unpack\n    def test_Add_newCategory(self, username, password, ImagePath, name, code, desc, leather_flag, unit):\n        self.LoginMethod.nativelogin(self.driver, username, password)\n        try:\n            self.assertEqual(self.Inventory.AddInventory_Items(ImagePath, name, code, desc, leather_flag, unit), True, msg=\"Adding a New Category Failed \")\n        # Checking if assertion failed\n        except AssertionError as e:\n            allure.attach(self.driver.get_screenshot_as_png(), name=\"Failed_for_customer\", attachment_type=AttachmentType.PNG)\n            self.log.error(f\"Assertion failed here while finding element. {str(e)}\")\n>           raise e\n\nTestInventory.py:47: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nTestInventory.py:42: in test_Add_newCategory\n    self.assertEqual(self.Inventory.AddInventory_Items(ImagePath, name, code, desc, leather_flag, unit), True, msg=\"Adding a New Category Failed \")\nC:\\Program Files\\JetBrains\\PyCharm Community Edition 2022.3.3\\plugins\\python-ce\\helpers\\pycharm\\teamcity\\diff_tools.py:33: in _patched_equals\n    old(self, first, second, msg)\nE   AssertionError: None != True : Adding a New Category Failed","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"testStage":{"status":"failed","statusMessage":"AssertionError: None != True : Adding a New Category Failed","statusTrace":"self = <TestsCases.TestInventory.TestInventory testMethod=test_Add_newCategory_1___frugal_latido_com_np____Test_123____E___PO...oryData__Image__BikerJacket_jpg____Leather01____LT01____This_is_from_an_automated_Script___for_Leather___01___1__None_>\nusername = 'frugal@latido.com.np', password = 'Test@123'\nImagePath = 'E:\\\\POM_for_Bottle\\\\WebApp\\\\TestData\\\\InventoryData\\\\Image\\\\BikerJacket.jpg'\nname = 'Leather01', code = 'LT01'\ndesc = 'This is from an automated Script ( for Leather ) 01', leather_flag = 1\nunit = None\n\n    @allure.title(f\"Create a new Category\")\n    @allure.story(\"Create a new Category from Add button \")\n    @allure.severity(allure.severity_level.NORMAL)\n    @data(*Utils.read_xlsx(\"../TestData/InventoryData/InventoryTestCase.xlsx\", \"TestInventory\"))\n    @unpack\n    def test_Add_newCategory(self, username, password, ImagePath, name, code, desc, leather_flag, unit):\n        self.LoginMethod.nativelogin(self.driver, username, password)\n        try:\n            self.assertEqual(self.Inventory.AddInventory_Items(ImagePath, name, code, desc, leather_flag, unit), True, msg=\"Adding a New Category Failed \")\n        # Checking if assertion failed\n        except AssertionError as e:\n            allure.attach(self.driver.get_screenshot_as_png(), name=\"Failed_for_customer\", attachment_type=AttachmentType.PNG)\n            self.log.error(f\"Assertion failed here while finding element. {str(e)}\")\n>           raise e\n\nTestInventory.py:47: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\nTestInventory.py:42: in test_Add_newCategory\n    self.assertEqual(self.Inventory.AddInventory_Items(ImagePath, name, code, desc, leather_flag, unit), True, msg=\"Adding a New Category Failed \")\nC:\\Program Files\\JetBrains\\PyCharm Community Edition 2022.3.3\\plugins\\python-ce\\helpers\\pycharm\\teamcity\\diff_tools.py:33: in _patched_equals\n    old(self, first, second, msg)\nE   AssertionError: None != True : Adding a New Category Failed","steps":[],"attachments":[{"uid":"290c157d4861f190","name":"Failed_for_customer","source":"290c157d4861f190.png","type":"image/png","size":118314},{"uid":"d0799acb071a366a","name":"log","source":"d0799acb071a366a.txt","type":"text/plain","size":131}],"parameters":[],"attachmentsCount":2,"shouldDisplayMessage":true,"stepsCount":0,"hasContent":true},"afterStages":[],"labels":[{"name":"feature","value":"Inventory"},{"name":"severity","value":"normal"},{"name":"story","value":"Create a new Category from Add button "},{"name":"suite","value":"TestInventory"},{"name":"subSuite","value":"TestInventory"},{"name":"host","value":"0day"},{"name":"thread","value":"5116-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"TestInventory"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Product defects","matchedStatuses":[],"flaky":false}],"tags":[]},"source":"5ed462220228c9.json","parameterValues":[]}